version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: musik_client
    volumes:
      - ./client/src:/app/src
    networks:
      - main

  backend:
    env_file: ./backend/.env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: musik_server
    volumes:
      - ./backend/src:/usr/src/app/src
    networks:
      - main

  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - main

networks:
  main:
