version: '3'

services:
  node:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musik
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - main

networks:
  main: